### ISSUE TITLE
[FR] Admin Auth

### ISSUE THREAD

**Issue by Sloth-on-meth** [mandarons/yadd#11]
**Is your feature request related to a problem? Please describe.**
I need authentication to be possible 

**Describe the solution you'd like**
I'd like a simple auth system

**Describe alternatives you've considered**
traefik auth but I just cannot get it to work

**Comment by mandarons** [comment]
Do  you just want a single user auth (usually `admin`) or multi-user auth (usually needs user registration etc.)?

**Comment by mandarons** [comment]
Use case: As a user, I want to have optional password protection so that I can secure the access to the dashboard, if required.

Admin password is enabled through configuration or environment variable.
