### ISSUE TITLE
Not reporting correctly on all services

### ISSUE THREAD

**Issue by dnburgess** [mandarons/yadd#7]
From Reddit: I deliberately shut down my YouTubeDL container and have waited several minutes as well as have refreshed the status page, but it is still telling me that the service is up. I even restarted YADD and refreshed the status page and it is still telling me that YouTubeDL is up (green) despite the service not loading when I click the icon on the dashboard.

**Comment by mandarons** [comment]
@dnburgess Thank you very much for submitting this improvement opportunity! I appreciate you taking some time to test the application. 👍
